### ISSUE TITLE
[ERROR] Hardware bridge: we've missed 7 requests

### ISSUE THREAD

**Issue by QiayuanLiao** [mit-biomimetics/Cheetah-Software#10]
Sometimes when I running the controller on the UP board and the sim on a laptop, UP board looks like it can receive part of messages, but some missed. A figure is as follows.
Note: I have ruined this system successfully in another network environment.
![Screenshot from 2019-10-13 23-48-09](https://user-images.githubusercontent.com/21256355/66718565-dcf1bf80-ee17-11e9-9ca6-3435e57186cc.png)

**Comment by HorsonLiu** [comment]
LCM 是基于 UDP 组播发送的消息，本身就不可靠，加上 1000 hz 的高频，所以对网络要求是比较高的，如果是无线网会有大量丢包，用有线直连或者有线连单独的路由器是可以的。
LCM is based on UDP multicast which is not reliable.

**Comment by QiayuanLiao** [comment]
整个路由器只有这两个设备，而且离得非常近，这种程度的丢包不正常吧？

**Comment by dicarlo236** [comment]
It seems like you are getting dropped network packets.  At this point, it isn't even sending log data at 1000 Hz, it is just sending over the parameters in the GUI, so there shouldn't be a lot of traffic.

 I would check that your network cable is not damaged, and maybe try without a router/switch in between?  We have never seen this issue.

**Comment by QiayuanLiao** [comment]
I use both wireless and wired through the route, but it still doesn't work. I have tied 3 route and it works on one route. Maybe I need to change some settings?

**Comment by HorsonLiu** [comment]
While running, the ctrl side (up board) keep sending datas in 1KHz （even though no use of these datas）. Comment them, then no packets will be lost. 
`void RobotRunner::finalizeStep() {
  if (robotType == RobotType::MINI_CHEETAH) {
    _legController->updateCommand(spiCommand);
  } else if (robotType == RobotType::CHEETAH_3) {
    _legController->updateCommand(tiBoardCommand);
  } else {
    assert(false);
  }
  _legController->setLcm(&leg_control_data_lcm, &leg_control_command_lcm);
  _stateEstimate.setLcm(state_estimator_lcm);
  _lcm.publish("leg_control_command", &leg_control_command_lcm);
  _lcm.publish("leg_control_data", &leg_control_data_lcm);
  _lcm.publish("state_estimator", &state_estimator_lcm);
  _iterations++;
}`
