### ISSUE TITLE
Simulation Error

### ISSUE THREAD

**Issue by jimy92** [mit-biomimetics/Cheetah-Software#11]
Hi,
    I updated the code on October 14th, successfully compiled，and when I ran the simulation on user computer,there are some mistakes.

    my code:
        $ ./sim/sim
        $ ./user/MIT_Controller/mit_ctrl m s

    Error:
        " Simulation Error
          Control code has an error:
          Control parameter testValue wasn't found in parameter collection user-parameters"

Running a test program has one that always fails
    $ ./common/test-common
    [  FAILED  ] LegController.FwdKinematicsLegSign

Is it something I did wrong or missed some important steps?

**Comment by HorsonLiu** [comment]
Load mc-mit-ctrl-user-parameters.yaml first.

**Comment by jimy92** [comment]
Thank you very much.

If there is no game controller, how to run the simulation program ?

**Comment by QiayuanLiao** [comment]
You can run simulation without ganpad.

**Comment by dicarlo236** [comment]
Sorry, this was our issue, it should be fixed by b99d1a3f7ee59a41d23921ea5f1c515afd1db130

Without a gamepad, you can still run the simulator, but you won't be able to command it to walk around.  We use the Logitech F310 gamepad, but I think most similar-looking controllers will also work.

**Comment by jimy92** [comment]
Thank，
The simulation is working.

Now, when I run the simulation, the dog is shivering on the ground, not standing up. When I click the button "go home", it just jump and then shiver on the ground.
I don't have a joystick，Is this right?

**Comment by jimy92** [comment]
Good! I saw it in "Robot Control Parameters"

**Comment by dicarlo236** [comment]
Unfortunately, we don't have documentation for all of them yet, and many are currently unused.  Most of them are related to gains for the state estimator.

For running the MIT controller with the USB game controller, you should set "use_rc" to 0.

**Comment by simanxu** [comment]
> Unfortunately, we don't have documentation for all of them yet, and many are currently unused. Most of them are related to gains for the state estimator.
> 
> For running the MIT controller with the USB game controller, you should set "use_rc" to 0.

This quote really helped me!!! And could you explain the usefulness of use_rc?

**Comment by simanxu** [comment]
> > Unfortunately, we don't have documentation for all of them yet, and many are currently unused. Most of them are related to gains for the state estimator.
> > For running the MIT controller with the USB game controller, you should set "use_rc" to 0.
> 
> This quote really helped me!!! And could you explain the usefulness of use_rc?

I got it, use_rc = use R/C radios which is conflicts to USB gamepad
