### ISSUE TITLE
Error opening /dev/ttyUSB0: No such file or directory

### ISSUE THREAD

**Issue by rshum19** [mit-biomimetics/Cheetah-Software#13]
Hi,

First I want to thank you for having all this code/software open source! 

I believe I have compiled and installed the software correctly. However, I'm having issues running the simulation with the MIT controller. 

When I run:
```
user/MIT_Controller/mit_ctrl m s
```

I get the following error
```
[run_sbus] starting...
Error opening /dev/ttyUSB0: No such file or directory
ESTOP!
ESTOP!
ESTOP!
```

Is the opening of the /dev/ttyUSB0 has to do with the Logitech F310 gamepad? I am trying to use a Logitech F710 instead.

Thank you,

**Comment by dicarlo236** [comment]
Hi,

The simulator supports two different types of controllers - the Logitech F310 gamepad, and an R/C transmitter normally used for model planes.  This error is related to the R/C transmitter code, and not the Logitech gamepad code, so you can just ignore it if you're using the Logitech F310.

Once you've started both the simulator and the robot, you need to configure the simulator to use the Logitech F310 by changing `use_rc` in the Robot Control Parameters column of the simulator GUI to 0 and pressing enter.

**Comment by rshum19** [comment]
Hi, 

Thank you for the prompt response. That solved it. I'm closing the issue.
