### ISSUE TITLE
[  FAILED  ] LegController.FwdKinematicsLegSign

### ISSUE THREAD

**Issue by yonchien** [mit-biomimetics/Cheetah-Software#14]
I used the common/test-common ,it error[  FAILED  ] 1 test, listed below:[  FAILED  ] LegController.FwdKinematicsLegSign

![Screenshot from 2019-11-06 23-03-23](https://user-images.githubusercontent.com/37019390/68309621-a98a1400-00e9-11ea-8f57-063dab604daa.png)

**Comment by dhkim0821** [comment]
It was because of the model update of mini-cheetah robot. We fixed it now. It must not have the failure anymore.
