### ISSUE TITLE
Keyboard control in sim? What hardware/software gamepad to use with sim?

### ISSUE THREAD

**Issue by stevenjj** [mit-biomimetics/Cheetah-Software#15]
Hello!
I am able to simulate the robots in sim after running
````
./sim/sim 
````
and using one of the controllers eg:
````
./user/WBC_Controller/wbc_ctrl m s
````
I can get the mini cheetah to the prone position after turning off the `use_rc` boolean, and it immediately performs a backflip, which is quite neat. 

However, I can't get the robot to stand up/walk around. It seems like having the gamepad controls is necessary.  Is there a keyboard based control? If not, what is the hardware used for sending commands?

Thanks!

**Comment by dhkim0821** [comment]
The current version does not support wbc_ctrl. Please use 'mit_ctrl.' We will remove WBC_Controller in the next update. 
For the keyboard based control, we do not support the keyboard based control unfortunately. You can use xbox controller.
