### ISSUE TITLE
Any hint to run the code 

### ISSUE THREAD

**Issue by YuehChuan** [mit-biomimetics/Cheetah-Software#18]
I followed the tutorial, code compiled, but nothing happen
![cheeta2](https://user-images.githubusercontent.com/7314531/69618669-3d118d80-1075-11ea-8afe-326f859ed235.png)

**Comment by xingkongyangwang** [comment]
Hi, I am runing on my computer. But there is many development environmental issues. Some paths and files are not found.
Can you write your process  in detail？ 
Thank you very much!

**Comment by dicarlo236** [comment]
@YuehChuan 
You are running a robot controller for Cheetah 3 - it says in the terminal that "Quadruped: Cheetah 3", but you have selected "Mini Cheetah" in the simulator.  The documentation https://github.com/mit-biomimetics/Cheetah-Software/blob/master/documentation/getting_started.md  will show how to run a controller for Mini Cheetah.  You also need to start the simulator before starting the robot code.

@xingkongyangwang 
See the documentation here https://github.com/mit-biomimetics/Cheetah-Software/blob/master/documentation/getting_started.md

If you still have trouble, you can post the error messages.

**Comment by YuehChuan** [comment]
@xingkongyangwang  
as a follow up, here is the LCM install steps in details.
https://hackmd.io/j4nHoQ16Rj-BV2NurgRZjA
I will document steps what  I did.   
 Thank you @dicarlo236 !
I will try it.
