### ISSUE TITLE
what about JCQP?

### ISSUE THREAD

**Issue by yonchien** [mit-biomimetics/Cheetah-Software#19]
What is the third-party library JCQP used for? is it  used with qpoases. I can not foud the JCQP throuth the internet. how can i get it .  if I want to use the osqp instead qpoases，how can i do ?
i found you use the osqpeigen. but you  do not install in the third party ? how can i install in the third party. i tried  install but it not work. how can i install osqpeigen.

**Comment by dicarlo236** [comment]
JCQP was a QP solver, but it is not very good so we don't use it anymore.  qpOASES is the only solver needed, and it is already in the third party folder and doesn't need to be installed.  You don't need to install any qp libraries yourself.

If you are having trouble with compiling, you can share the specific error messages and we can help you.
