### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by erwincoumans** [mit-biomimetics/Cheetah-Software#2]
Thanks for this software!
Can you provide a license file for this repository? Do you use the MIT license for this simulator?

**Comment by dhkim0821** [comment]
Yes, we use MIT license except some libraries in third-party.

**Comment by erwincoumans** [comment]
Thanks a lot for the update. Could you please add a LICENSE.txt file to this repository?
You can simply copy the text from https://opensource.org/licenses/MIT and add the name and year.

**Comment by dicarlo236** [comment]
Sorry, I thought I had added a license file a long time ago.  I have added it now.

**Comment by SteveMacenski** [comment]
@dhkim0821 the license is still not in the repository

**Comment by dicarlo236** [comment]
@SteveMacenski Sorry, we accidentally removed the License file this morning.  It is back now!

**Comment by SteveMacenski** [comment]
What was the reason for the force push to remove all the prior content?

**Comment by dicarlo236** [comment]
Our development code and our public code were very out of sync, and this was the easiest way to update it.  I believe the only thing we've removed is broken experimental controllers that were causing people confusion and making it harder for others to build the software.  If there's anything missing, let me know and we can add it back.

**Comment by SteveMacenski** [comment]
Got it, so is this more in sync?

I suppose its just not awesome practice to force push and kill the git history (that's normally done when there's something someone's trying to hide). I'm not specifically right now a user of this codebase to know if that messed anything else up or if there's something missing but that did raise some eye brows.

(though I'd love to be a user of this codebase and buy a cheetah mini, whenever those are available for research folks)

**Comment by dicarlo236** [comment]
We aren't trying to hide anything - feel free to check any of the 116 public forks of the repository.  The old repository was very large and had commits checking in huge amounts of unneeded files.

**Comment by SteveMacenski** [comment]
No worries, I didn't think that was the case either. Just a note.
