### ISSUE TITLE
There is an error while building the code

### ISSUE THREAD

**Issue by lyzjz** [mit-biomimetics/Cheetah-Software#22]
/home/huangqifeng/Downloads/master/sim/src/SimControlPanel.cpp: In lambda function:
/home/huangqifeng/Downloads/master/sim/src/SimControlPanel.cpp:408:12: error: no matching function for call to ‘QMetaObject::invokeMethod(SimControlPanel*, SimControlPanel::on_startButton_clicked()::<lambda()>::<lambda(std::__cxx11::string)>::<lambda()>)’
           });
            ^

**Comment by dicarlo236** [comment]
what version of Qt do you have installed?  what OS are you on?

**Comment by lyzjz** [comment]
> what version of Qt do you have installed? what OS are you on?

Most grateful for your reply. I am using Qt5.9.0 on ubuntu18.04.

**Comment by dicarlo236** [comment]
I would try with a newer version of Qt.  In 5.10.0 they added some new overloads to `QMetaObject::invokeMethod`.

See here:
https://doc-snapshots.qt.io/qt5-5.10/qmetaobject.html#invokeMethod-4
it says "This function was introduced in Qt 5.10."

**Comment by raess1** [comment]
I get the same error. 
I have tried qt versions:
5.9.9
5.12.0
5.12.10
5.15

Any other suggestions to solve this? 🤔
