### ISSUE TITLE
Cann't find Qt5Gamepad

### ISSUE THREAD

**Issue by QiayuanLiao** [mit-biomimetics/Cheetah-Software#4]
When I run on the ubuntu 18.04 
`cmake ..`
I got 
```
Scanning dependencies of target googletest-download
[ 11%] Skipping update step for 'googletest-download'
[ 22%] No configure step for 'googletest-download'
[ 33%] No build step for 'googletest-download'
[ 44%] No install step for 'googletest-download'
[ 55%] No test step for 'googletest-download'
[ 66%] Completed 'googletest-download'
[100%] Built target googletest-download
/home/qiayuanliao/Project/Cheetah-Software/build/googletest-src
/home/qiayuanliao/Project/Cheetah-Software/build/googletest-build
-- /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.9.5
CMake Warning at sim/CMakeLists.txt:44 (find_package):
  By not providing "FindQt5Gamepad.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Gamepad", but CMake did not find one.
  Could not find a package configuration file provided by "Qt5Gamepad" with
  any of the following names:
    Qt5GamepadConfig.cmake
    qt5gamepad-config.cmake
  Add the installation prefix of "Qt5Gamepad" to CMAKE_PREFIX_PATH or set
  "Qt5Gamepad_DIR" to a directory containing one of the above files.  If
  "Qt5Gamepad" provides a separate development package or SDK, be sure it has
  been installed. 
```
but I can run the Qt5 Gamepad on Qt Creator

**Comment by WatsonZhouAnda** [comment]
May I ask how you solved this problem? I encountered the same with you

**Comment by QiayuanLiao** [comment]
Check your CMakeList in /sim and make sure the path to qt is correct( check the version)
For me, I have to change to 
```
set(Qt5Core_DIR ~/Qt/5.12.4/gcc_64/lib/cmake/Qt5Core)
set(Qt5Widgets_DIR ~/Qt/5.12.4/gcc_64/lib/cmake/Qt5Widgets)
set(Qt5Gamepad_DIR ~/Qt/5.12.4/gcc_64/lib/cmake/Qt5Gamepad)
```

**Comment by WatsonZhouAnda** [comment]
Get it! 
Thanks!




 
From: Qiayuan
Date: 2019-11-18 18:25
To: mit-biomimetics/Cheetah-Software
CC: Zhou Anda; Comment
Subject: Re: [mit-biomimetics/Cheetah-Software] Cann't find Qt5Gamepad (#4)
Check your CMakeList in /sim and make sure the path to qt is correct( check the version)
For me, I have to change to
set(Qt5Core_DIR ~/Qt/5.12.4/gcc_64/lib/cmake/Qt5Core)
set(Qt5Widgets_DIR ~/Qt/5.12.4/gcc_64/lib/cmake/Qt5Widgets)
set(Qt5Gamepad_DIR ~/Qt/5.12.4/gcc_64/lib/cmake/Qt5Gamepad)

**Comment by eborghi10** [comment]
If you install `libqt5gamepad5-dev` with `sudo apt-get install -y libqt5gamepad5-dev` there's no need to make any change.

**Comment by Hjrmkk** [comment]
> If you install `libqt5gamepad5-dev` with `sudo apt-get install -y libqt5gamepad5-dev` there's no need to make any change.

Thank you. problem solved!
