### ISSUE TITLE
difficuilty encounter during compiling

### ISSUE THREAD

**Issue by WSPeng** [mit-biomimetics/Cheetah-Software#6]
Hi, 

I am following the compiling steps but I got some problems.

The output of "camke .." in Cheetah-Software/build is (partly):
"
runtime library [libQt5Widgets.so.5] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/shupeng/Qt5.12.4/5.12.4/gcc_64/lib
    runtime library [libQt5Gui.so.5] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/shupeng/Qt5.12.4/5.12.4/gcc_64/lib
  Some of these libraries may not be found correctly.
"
And the output of "./scripts/make_types.sh" : (partly)
"
rm: cannot remove '*/*.class': No such file or directory
rm: cannot remove '*/*.pyc': No such file or directory
Notice: enclosing LCM types without package into java namespace 'lcmtypes'.
cp: cannot stat '/usr/local/share/java/lcm.jar': No such file or directory

"
And the make process is terminated after 76%..

I followed all the instruction and installed all the required packages..

**Comment by dicarlo236** [comment]
Can you post the full output of what happens when you run `make` so I can see what exactly is going wrong?  

The `cmake ..` warning is something I've seen before but I haven't heard of it causing issues.  The `make_types.sh` output is correct.

You can also try going to the file `sim/CMakeLists.txt` and updating all the references to `5.10.0` to `5.12.4`, which seems like the version you have installed.

If you're on a newer version of Ubuntu, (18.04 and newer, I think), you can install Qt5 using `apt-get` and it will work fine.  If you're on an older version, you'll need to install it manually because the version from `apt` doesn't have the gamepad library.

**Comment by JacobShenHdu** [comment]
Hi,I met another problem during compiling.
I run 'make -j4' in Cheetah-Software/build and the output is:

jacob@jacob-ubuntu:~/MIT/Cheetah-Software/build$ make -j4
Scanning dependencies of target inih
Scanning dependencies of target Goldfarb_Optimizer
Scanning dependencies of target dynacore_yaml-cpp
Scanning dependencies of target libvnc
[  0%] Building C object third-party/inih/CMakeFiles/inih.dir/ini.c.o
[  0%] Building CXX object third-party/Goldfarb_Optimizer/CMakeFiles/Goldfarb_Optimizer.dir/Array.cc.o

**c++: error: unrecognized command line option ‘-no-pie’
third-party/Goldfarb_Optimizer/CMakeFiles/Goldfarb_Optimizer.dir/build.make:62: recipe for target 'third-party/Goldfarb_Optimizer/CMakeFiles/Goldfarb_Optimizer.dir/Array.cc.o' failed
make[2]: *** [third-party/Goldfarb_Optimizer/CMakeFiles/Goldfarb_Optimizer.dir/Array.cc.o] Error 1
CMakeFiles/Makefile2:193: recipe for target 'third-party/Goldfarb_Optimizer/CMakeFiles/Goldfarb_Optimizer.dir/all' failed
make[1]: *** [third-party/Goldfarb_Optimizer/CMakeFiles/Goldfarb_Optimizer.dir/all] Error 2
make[1]: *** Waiting for unfinished tasks....**

[  0%] Building CXX object third-party/inih/CMakeFiles/inih.dir/INIReader.cpp.o

**c++: error: unrecognized command line option ‘-no-pie’
third-party/inih/CMakeFiles/inih.dir/build.make:75: recipe for target 'third-party/inih/CMakeFiles/inih.dir/INIReader.cpp.o' failed
make[2]: *** [third-party/inih/CMakeFiles/inih.dir/INIReader.cpp.o] Error 1
make[2]: ***Waiting for unfinished tasks....**

[  0%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/binary.cpp.o
[  0%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/convert.cpp.o
[  1%] Building C object third-party/vectornav/CMakeFiles/libvnc.dir/src/vn/xplat/criticalsection.c.o

**cc: error: unrecognized command line option ‘-no-pie’
third-party/vectornav/CMakeFiles/libvnc.dir/build.make:62: recipe for target 'third-party/vectornav/CMakeFiles/libvnc.dir/src/vn/xplat/criticalsection.c.o' failed
make[2]: *** [third-party/vectornav/CMakeFiles/libvnc.dir/src/vn/xplat/criticalsection.c.o] Error 1
CMakeFiles/Makefile2:815: recipe for target 'third-party/vectornav/CMakeFiles/libvnc.dir/all' failed
make[1]: *** [third-party/vectornav/CMakeFiles/libvnc.dir/all] Error 2**

[  1%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/directives.cpp.o
**CMakeFiles/Makefile2:368: recipe for target 'third-party/inih/CMakeFiles/inih.dir/all' failed
make[1]: *** [third-party/inih/CMakeFiles/inih.dir/all] Error 2**
[  2%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/emit.cpp.o
[  2%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/emitfromevents.cpp.o
[  2%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/emitter.cpp.o
[  2%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/emitterstate.cpp.o
[  2%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/emitterutils.cpp.o
[  2%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/exceptions.cpp.o
[  2%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/exp.cpp.o
[  3%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/memory.cpp.o
[  3%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/node.cpp.o
[  3%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/node_data.cpp.o
[  3%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/nodebuilder.cpp.o
[  3%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/nodeevents.cpp.o
[  3%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/null.cpp.o
[  4%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/ostream_wrapper.cpp.o
[  4%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/parse.cpp.o
[  4%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/parser.cpp.o
[  4%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/regex_yaml.cpp.o
[  4%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/scanner.cpp.o
[  4%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/scanscalar.cpp.o
[  5%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/scantag.cpp.o
[  5%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/scantoken.cpp.o
[  5%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/simplekey.cpp.o
[  5%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/singledocparser.cpp.o
[  5%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/stream.cpp.o
[  5%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/tag.cpp.o
[  5%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/contrib/graphbuilder.cpp.o
[  6%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/contrib/graphbuilderadapter.cpp.o
[  6%] Linking CXX shared library libdynacore_yaml-cpp.so
[  6%] Built target dynacore_yaml-cpp
**Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2**

what could be the cause of the problem?Thank you.

**Comment by dicarlo236** [comment]
I think some versions of `gcc` don't have the `-no-pie` option. First I would try updating your compiler -  this option might not have been available in older version. If that doesn't fix it, you could try removing the `-no-pie` flag from all the `CMakeLists.txt` files in the repository and it might work.  The software is only tested/supported on Ubuntu 16.04, 18.04, and 18.10, so you might have other problems if you aren't using one of these.  

What operating system/compiler do you have?  Can you post the output of `c++ -v`?

**Comment by WSPeng** [comment]
> Can you post the full output of what happens when you run `make` so I can see what exactly is going wrong?
> 
> The `cmake ..` warning is something I've seen before but I haven't heard of it causing issues. The `make_types.sh` output is correct.
> 
> You can also try going to the file `sim/CMakeLists.txt` and updating all the references to `5.10.0` to `5.12.4`, which seems like the version you have installed.
> 
> If you're on a newer version of Ubuntu, (18.04 and newer, I think), you can install Qt5 using `apt-get` and it will work fine. If you're on an older version, you'll need to install it manually because the version from `apt` doesn't have the gamepad library.

I managed to install the package successfully. I uninstalled the Qt 5.12.4 and installed the 5.10.0, and reinstalled the LCM, and the compiling is good now.

Thanks!

**Comment by JacobShenHdu** [comment]
> I think some versions of `gcc` don't have the `-no-pie` option. First I would try updating your compiler - this option might not have been available in older version. If that doesn't fix it, you could try removing the `-no-pie` flag from all the `CMakeLists.txt` files in the repository and it might work. The software is only tested/supported on Ubuntu 16.04, 18.04, and 18.10, so you might have other problems if you aren't using one of these.
> 
> What operating system/compiler do you have? Can you post the output of `c++ -v`?

Thank you! I updated gcc and g++ to 5.5(the old is 4.8), and this problem did not recur. Now I can run simulator successfully. If I want to control mini cheetah, is a game handle necessary? and what kind handle can work?

**Comment by WSPeng** [comment]
The problem is solved
