### ISSUE TITLE
AutoUic subprocess error

### ISSUE THREAD

**Issue by yingya1992** [mit-biomimetics/Cheetah-Software#61]
[ 33%] Building CXX object third-party/qpOASES/CMakeFiles/qpOASES.dir/src/Flipper.cpp.o
[ 33%] Building C object third-party/JCQP/CMakeFiles/JCQP.dir/amd/src/amd_control.c.o
[ 33%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/stream.cpp.o
[ 33%] Building CXX object third-party/qpOASES/CMakeFiles/qpOASES.dir/src/Indexlist.cpp.o
[ 33%] Building CXX object third-party/qpOASES/CMakeFiles/qpOASES.dir/src/LAPACKReplacement.cpp.o
[ 34%] Building CXX object third-party/qpOASES/CMakeFiles/qpOASES.dir/src/Matrices.cpp.o
[ 34%] Building CXX object third-party/qpOASES/CMakeFiles/qpOASES.dir/src/MessageHandling.cpp.o
[ 35%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/tag.cpp.o
[ 35%] Building CXX object third-party/lord_imu/CMakeFiles/test_imu.dir/test/lord_test.cpp.o
[ 35%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/contrib/graphbuilder.cpp.o
[ 35%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_yaml-cpp.dir/src/contrib/graphbuilderadapter.cpp.o
[ 35%] Building CXX object third-party/qpOASES/CMakeFiles/qpOASES.dir/src/OQPinterface.cpp.o
[ 35%] Linking CXX shared library libdynacore_yaml-cpp.so
[ 36%] Linking CXX executable test_imu
[ 36%] Built target test_imu
[ 36%] Building CXX object third-party/qpOASES/CMakeFiles/qpOASES.dir/src/Options.cpp.o
[ 36%] Built target dynacore_yaml-cpp
[ 37%] Building CXX object third-party/qpOASES/CMakeFiles/qpOASES.dir/src/QProblem.cpp.o
[ 37%] Building CXX object googletest-build/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[ 37%] Building C object third-party/JCQP/CMakeFiles/JCQP.dir/amd/src/amd_defaults.c.o
[ 37%] Building CXX object third-party/qpOASES/CMakeFiles/qpOASES.dir/src/QProblemB.cpp.o
[ 38%] Building C object third-party/JCQP/CMakeFiles/JCQP.dir/amd/src/amd_info.c.o
[ 39%] Building CXX object user/MIT_Controller/Controllers/WBC/WBIC/CMakeFiles/WBIC.dir/KinWBC.cpp.o
[ 39%] Building CXX object third-party/qpOASES/CMakeFiles/qpOASES.dir/src/SQProblem.cpp.o
[ 40%] Building CXX object third-party/qpOASES/CMakeFiles/qpOASES.dir/src/SQProblemSchur.cpp.o
[ 40%] Building CXX object third-party/qpOASES/CMakeFiles/qpOASES.dir/src/SolutionAnalysis.cpp.o
[ 40%] Building CXX object third-party/qpOASES/CMakeFiles/qpOASES.dir/src/SparseSolver.cpp.o
[ 40%] Building CXX object third-party/qpOASES/CMakeFiles/qpOASES.dir/src/SubjectTo.cpp.o
[ 41%] Building CXX object third-party/qpOASES/CMakeFiles/qpOASES.dir/src/Utils.cpp.o
[ 41%] Linking CXX shared library libs/libqpOASES.so
[ 41%] Built target qpOASES
[ 41%] Building CXX object user/MIT_Controller/Controllers/WBC/WBIC/CMakeFiles/WBIC.dir/WBIC.cpp.o
[ 41%] Building C object third-party/JCQP/CMakeFiles/JCQP.dir/amd/src/amd_order.c.o
[ 41%] Building C object third-party/JCQP/CMakeFiles/JCQP.dir/amd/src/amd_post_tree.c.o
[ 42%] Building C object third-party/JCQP/CMakeFiles/JCQP.dir/amd/src/amd_postorder.c.o
[ 42%] Building C object third-party/JCQP/CMakeFiles/JCQP.dir/amd/src/amd_preprocess.c.o
[ 42%] Building C object third-party/JCQP/CMakeFiles/JCQP.dir/amd/src/amd_valid.c.o
[ 42%] Building C object third-party/JCQP/CMakeFiles/JCQP.dir/amd/src/SuiteSparse_config.c.o
[ 43%] Linking CXX shared library libJCQP.so
[ 43%] Built target JCQP
[ 43%] Building CXX object third-party/ParamHandler/CMakeFiles/dynacore_param_handler.dir/ParamHandler.cpp.o
[ 44%] Linking CXX shared library libdynacore_param_handler.so
[ 44%] Built target dynacore_param_handler
[ 44%] Building C object third-party/osqp/CMakeFiles/osqp.dir/src/auxil.c.o
[ 44%] Building C object third-party/osqp/CMakeFiles/osqp.dir/src/cs.c.o
[ 45%] Building C object third-party/osqp/CMakeFiles/osqp.dir/src/ctrlc.c.o
[ 45%] Building C object third-party/osqp/CMakeFiles/osqp.dir/src/kkt.c.o
[ 46%] Linking CXX static library ../../lib/libgtest.a
[ 46%] Building C object third-party/osqp/CMakeFiles/osqp.dir/src/lin_alg.c.o
[ 46%] Built target gtest
[ 46%] Building C object third-party/osqp/CMakeFiles/osqp.dir/src/lin_sys.c.o
[ 47%] Building C object third-party/osqp/CMakeFiles/osqp_demo.dir/examples/osqp_demo.c.o
[ 47%] Linking C executable out/osqp_demo
[ 48%] Building C object third-party/osqp/CMakeFiles/osqp.dir/src/osqp.c.o
[ 48%] Built target osqp_demo
[ 48%] Building C object third-party/osqp/CMakeFiles/osqp.dir/src/polish.c.o
[ 48%] Building C object third-party/osqp/lin_sys/direct/qdldl/qdldl_sources/CMakeFiles/qdldl_example.dir/examples/c/example.c.o
[ 49%] Linking C executable out/qdldl_example
[ 49%] Building C object third-party/osqp/CMakeFiles/osqp.dir/src/proj.c.o
[ 49%] Built target qdldl_example
[ 50%] Building C object third-party/osqp/CMakeFiles/osqp.dir/src/scaling.c.o
[ 50%] Building CXX object googletest-build/googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.o
[ 50%] Building C object third-party/osqp/CMakeFiles/osqp.dir/src/util.c.o
[ 50%] Building C object third-party/osqp/CMakeFiles/osqp.dir/lin_sys/lib_handler.c.o
[ 50%] Linking C shared library out/libosqp.so
[ 50%] Built target osqp
[ 50%] Building CXX object googletest-build/googletest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[ 50%] Linking CXX static library ../../lib/libgtest_main.a
[ 50%] Built target gtest_main
[ 50%] Building CXX object common/CMakeFiles/biomimetics.dir/src/Collision/CollisionBox.cpp.o
[ 51%] Building CXX object common/CMakeFiles/biomimetics.dir/src/Collision/CollisionMesh.cpp.o
[ 52%] Linking CXX static library ../../lib/libgmock.a
[ 52%] Built target gmock
[ 52%] Building CXX object common/CMakeFiles/biomimetics.dir/src/Collision/CollisionPlane.cpp.o
[ 52%] Building CXX object googletest-build/googlemock/CMakeFiles/gmock_main.dir/src/gmock_main.cc.o
[ 52%] Building CXX object common/CMakeFiles/biomimetics.dir/src/Collision/ContactConstraint.cpp.o
[ 53%] Building CXX object common/CMakeFiles/biomimetics.dir/src/Collision/ContactImpulse.cpp.o
[ 53%] Linking CXX static library ../../lib/libgmock_main.a
[ 53%] Built target gmock_main
[ 53%] Building CXX object common/CMakeFiles/biomimetics.dir/src/Collision/ContactSpringDamper.cpp.o
[ 53%] Building CXX object common/CMakeFiles/biomimetics.dir/src/ControlParameters/ControlParameterInterface.cpp.o
[ 53%] Building CXX object common/CMakeFiles/biomimetics.dir/src/ControlParameters/ControlParameters.cpp.o
[ 54%] Building CXX object common/CMakeFiles/biomimetics.dir/src/Controllers/ContactEstimator.cpp.o
[ 54%] Building CXX object common/CMakeFiles/biomimetics.dir/src/Controllers/DesiredStateCommand.cpp.o
[ 54%] Building CXX object common/CMakeFiles/biomimetics.dir/src/Controllers/FootSwingTrajectory.cpp.o
[ 55%] Building CXX object common/CMakeFiles/biomimetics.dir/src/Controllers/GaitScheduler.cpp.o
[ 55%] Building CXX object common/CMakeFiles/biomimetics.dir/src/Controllers/LegController.cpp.o
[ 55%] Linking CXX shared library libWBIC.so
[ 55%] Built target WBIC
[ 55%] Building CXX object common/CMakeFiles/biomimetics.dir/src/Controllers/OrientationEstimator.cpp.o
[ 55%] Building CXX object common/CMakeFiles/biomimetics.dir/src/Controllers/PositionVelocityEstimator.cpp.o
[ 56%] Building CXX object common/CMakeFiles/biomimetics.dir/src/Dynamics/DynamicsSimulator.cpp.o
[ 56%] Building CXX object common/CMakeFiles/biomimetics.dir/src/Dynamics/FloatingBaseModel.cpp.o
[ 56%] Building CXX object common/CMakeFiles/biomimetics.dir/src/Dynamics/Quadruped.cpp.o
[ 57%] Building CXX object common/CMakeFiles/biomimetics.dir/src/SimUtilities/ImuSimulator.cpp.o
[ 57%] Building CXX object common/CMakeFiles/biomimetics.dir/src/SimUtilities/SpineBoard.cpp.o
[ 57%] Building CXX object common/CMakeFiles/biomimetics.dir/src/SimUtilities/ti_boardcontrol.cpp.o
[ 57%] Building CXX object common/CMakeFiles/biomimetics.dir/src/SparseCMPC/OsqpTriples.cpp.o
[ 58%] Building CXX object common/CMakeFiles/biomimetics.dir/src/SparseCMPC/SparseCMPC.cpp.o
[ 58%] Building CXX object common/CMakeFiles/biomimetics.dir/src/SparseCMPC/SparseCMPC_Math.cpp.o
[ 58%] Building CXX object common/CMakeFiles/biomimetics.dir/src/Utilities/PeriodicTask.cpp.o
[ 59%] Building CXX object common/CMakeFiles/biomimetics.dir/src/Utilities/SegfaultHandler.cpp.o
[ 59%] Building CXX object common/CMakeFiles/biomimetics.dir/src/Utilities/Utilities_print.cpp.o
[ 59%] Building CXX object common/CMakeFiles/biomimetics.dir/src/Utilities/filters.cpp.o
[ 59%] Building CXX object common/CMakeFiles/biomimetics.dir/src/Utilities/save_file.cpp.o
[ 60%] Building CXX object common/CMakeFiles/biomimetics.dir/src/Utilities/utilities.cpp.o
[ 60%] Linking CXX shared library libbiomimetics.so
[ 60%] Built target biomimetics
[ 61%] Automatic MOC and UIC for target sim
[ 62%] Building CXX object common/FootstepPlanner/CMakeFiles/footstep_planner.dir/GraphSearch.cpp.o

AutoUic subprocess error
------------------------
The uic process failed to compile
  "SRC:/sim/src/SimControlPanel.ui"
into
  "SRC:/mc-build/sim/sim_autogen/include/ui_SimControlPanel.h"
included by
  "SRC:/sim/src/SimControlPanel.cpp"

Command
-------
/opt/Qt5.10.0/5.10.0/gcc_64/bin/uic -o /media/ray/work/Github/Cheetah-Software/mc-build/sim/sim_autogen/include/ui_SimControlPanel.h /media/ray/work/Github/Cheetah-Software/sim/src/SimControlPanel.ui

Output
------
/opt/Qt5.10.0/5.10.0/gcc_64/bin/uic: relocation error: /opt/Qt5.10.0/5.10.0/gcc_64/bin/uic: symbol _ZdlPvm, version Qt_5 not defined in file libQt5Core.so.5 with link time reference

AutoUic subprocess error
------------------------
The uic process failed to compile
  "SRC:/sim/src/JoystickTest.ui"
into
  "SRC:/mc-build/sim/sim_autogen/include/ui_JoystickTest.h"
included by
  "SRC:/sim/src/JoystickTest.cpp"

Command
-------
/opt/Qt5.10.0/5.10.0/gcc_64/bin/uic -o /media/ray/work/Github/Cheetah-Software/mc-build/sim/sim_autogen/include/ui_JoystickTest.h /media/ray/work/Github/Cheetah-Software/sim/src/JoystickTest.ui

Output
------
/opt/Qt5.10.0/5.10.0/gcc_64/bin/uic: relocation error: /opt/Qt5.10.0/5.10.0/gcc_64/bin/uic: symbol _ZdlPvm, version Qt_5 not defined in file libQt5Core.so.5 with link time reference

[ 62%] Building CXX object common/CMakeFiles/test-common.dir/test/test_ControlParameters.cpp.o
[ 62%] Building CXX object robot/CMakeFiles/robot.dir/src/HardwareBridge.cpp.o

AutoUic subprocess error
------------------------
The uic process failed to compile
  "SRC:/sim/src/MiniCheetahDebug.ui"
into
  "SRC:/mc-build/sim/sim_autogen/include/ui_MiniCheetahDebug.h"
included by
  "SRC:/sim/src/MiniCheetahDebug.cpp"

Command
-------
/opt/Qt5.10.0/5.10.0/gcc_64/bin/uic -o /media/ray/work/Github/Cheetah-Software/mc-build/sim/sim_autogen/include/ui_MiniCheetahDebug.h /media/ray/work/Github/Cheetah-Software/sim/src/MiniCheetahDebug.ui

Output
------
/opt/Qt5.10.0/5.10.0/gcc_64/bin/uic: relocation error: /opt/Qt5.10.0/5.10.0/gcc_64/bin/uic: symbol _ZdlPvm, version Qt_5 not defined in file libQt5Core.so.5 with link time reference

sim/CMakeFiles/sim_autogen.dir/build.make:60: recipe for target 'sim/CMakeFiles/sim_autogen' failed
make[2]: *** [sim/CMakeFiles/sim_autogen] Error 1
CMakeFiles/Makefile2:2410: recipe for target 'sim/CMakeFiles/sim_autogen.dir/all' failed
make[1]: *** [sim/CMakeFiles/sim_autogen.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
[ 62%] Building CXX object robot/CMakeFiles/robot.dir/src/JPosInitializer.cpp.o
[ 62%] Linking CXX shared library libfootstep_planner.so
[ 62%] Built target footstep_planner
[ 63%] Building CXX object robot/CMakeFiles/robot.dir/src/RobotRunner.cpp.o
[ 64%] Building CXX object common/CMakeFiles/test-common.dir/test/test_ImuSimulator.cpp.o
[ 64%] Building CXX object robot/CMakeFiles/robot.dir/src/SimulationBridge.cpp.o
[ 64%] Building CXX object common/CMakeFiles/test-common.dir/test/test_JCQP.cpp.o
[ 64%] Building CXX object common/CMakeFiles/test-common.dir/test/test_LegController.cpp.o
[ 64%] Building CXX object robot/CMakeFiles/robot.dir/src/main_helper.cpp.o
[ 64%] Building CXX object robot/CMakeFiles/robot.dir/src/rt/rt_ethercat.cpp.o
[ 64%] Building CXX object common/CMakeFiles/test-common.dir/test/test_actuatorModel.cpp.o
[ 65%] Building CXX object robot/CMakeFiles/robot.dir/src/rt/rt_rc_interface.cpp.o
[ 66%] Building CXX object common/CMakeFiles/test-common.dir/test/test_casadi.cpp.o
[ 66%] Building CXX object robot/CMakeFiles/robot.dir/src/rt/rt_sbus.cpp.o
[ 66%] Building CXX object common/CMakeFiles/test-common.dir/test/test_cheetah3_model.cpp.o
[ 66%] Building CXX object robot/CMakeFiles/robot.dir/src/rt/rt_serial.cpp.o
[ 67%] Building CXX object robot/CMakeFiles/robot.dir/src/rt/rt_spi.cpp.o
[ 67%] Building CXX object robot/CMakeFiles/robot.dir/src/rt/rt_vectornav.cpp.o
[ 67%] Building CXX object common/CMakeFiles/test-common.dir/test/test_dynamics.cpp.o
[ 67%] Linking CXX shared library librobot.so
[ 67%] Built target robot
[ 68%] Building CXX object common/CMakeFiles/test-common.dir/test/test_filters.cpp.o
[ 68%] Building CXX object common/CMakeFiles/test-common.dir/test/test_footswing.cpp.o
[ 68%] Building CXX object common/CMakeFiles/test-common.dir/test/test_goldfarb.cpp.o
[ 68%] Building CXX object common/CMakeFiles/test-common.dir/test/test_math.cpp.o
[ 69%] Building CXX object common/CMakeFiles/test-common.dir/test/test_mini_cheetah_model.cpp.o
[ 69%] Building CXX object common/CMakeFiles/test-common.dir/test/test_orientation_tools.cpp.o
[ 69%] Building CXX object common/CMakeFiles/test-common.dir/test/test_osqp.cpp.o
[ 70%] Building CXX object common/CMakeFiles/test-common.dir/test/test_periodic_tasks.cpp.o
[ 70%] Building CXX object common/CMakeFiles/test-common.dir/test/test_sharedMemory.cpp.o
[ 70%] Building CXX object common/CMakeFiles/test-common.dir/test/test_spatial.cpp.o
[ 70%] Building CXX object common/CMakeFiles/test-common.dir/test/test_utilities.cpp.o
[ 71%] Building CXX object common/CMakeFiles/test-common.dir/test/test_yaml.cpp.o
[ 71%] Linking CXX executable test-common
[ 71%] Built target test-common
Makefile:132: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by skywoodsz** [comment]
Hi, how did you solve this problem?
