### ISSUE TITLE
Why there is  a dtMPC calculated in pfy_rel?

### ISSUE THREAD

**Issue by Derek-TH-Wang** [mit-biomimetics/Cheetah-Software#62]
This is the calculation on foot step planner(pf) in the code, along x direction, I think it is as same as the equation in the paper(picture 2), but along Y direction there is a dtMPC multiply in the equation as the picture show below(picture 1), but according to the paper, Psymmetry dose not need to multiply the dtMPC, I do not understand, who knows why? 

![image](https://user-images.githubusercontent.com/23303126/97842514-adfc0380-1d22-11eb-98fa-410b971792cb.png)

![image](https://user-images.githubusercontent.com/23303126/97842093-07176780-1d22-11eb-8f8e-63dc69a4abb2.png)

**Comment by YuXianYuan** [comment]
small mistake
