### ISSUE TITLE
Error when building 

### ISSUE THREAD

**Issue by raess1** [mit-biomimetics/Cheetah-Software#68]
I get the same error on Ubuntu 18.04.
I have tried qt versions:
5.9.9
5.12.0
5.12.10
5.15

Any other suggestions to solve this? 🤔

_Originally posted by @raess1 in https://github.com/mit-biomimetics/Cheetah-Software/issues/22#issuecomment-786335134_

**Comment by raess1** [comment]
moved set qt some lines up in cmake solved problem.

**Comment by ChaunceyWuLiu** [comment]
hello, i am having exactly same issue. Could you have a detail description on your solution. I couldn't get your point.
