### ISSUE TITLE
What's the function of rt_interface_lcm?

### ISSUE THREAD

**Issue by JacobShenHdu** [mit-biomimetics/Cheetah-Software#7]
It seems to read data from sbus, and modify the attributes of “**main_control_settings**” based on the data. But I don't know who send data to sbus , and who publish message on "**INTERFACE_gui_main_control_settings**" channel with LCM, and how does “**main_control_settings**” work in the program.

**Comment by dicarlo236** [comment]
We use this code to control the robot with a wireless R/C radio when testing untethered.  The radio receiver connects to the control computer with SBUS.  It is an alternative to the USB game controller, but also allows us to change the current mode (locomotion, standing, ...).  The LCM channel is no longer used, and nothing will send/receive messages with the "INTERFACE_gui_main_control_settings" (nothing ever calls the `init_interface_lcm` function).

**Comment by JacobShenHdu** [comment]
> We use this code to control the robot with a wireless R/C radio when testing untethered. The radio receiver connects to the control computer with SBUS. It is an alternative to the USB game controller, but also allows us to change the current mode (locomotion, standing, ...). The LCM channel is no longer used, and nothing will send/receive messages with the "INTERFACE_gui_main_control_settings" (nothing ever calls the `init_interface_lcm` function).

Thanks for your detailed explanation.
