### ISSUE TITLE
Hi I get stingop truncation error while compiling project ?

### ISSUE THREAD

**Issue by shivauchiha** [mit-biomimetics/Cheetah-Software#79]
I am currently building this project in ubuntu 20.04. I have installed all per-requisite libraries. While building, I get the error as shown in the below screenshot. should I ignore it by setting the appropriate flag ? Please Advice. Thank You.

![Screenshot from 2022-02-09 09-37-18](https://user-images.githubusercontent.com/41376183/153120460-1d9d32e7-f579-4e21-9721-75ef0236f630.png)

**Comment by shivauchiha** [comment]
This error didn't appear while using command make -j .

**Comment by shivauchiha** [comment]
Make -j crashesh the system as it eats up all the ram. 

Make -j4 gives the same issue as top mentioned one.

**Comment by shivauchiha** [comment]
I was able to compile using g++8 .

**Comment by physicsfreak963** [comment]
@shivauchiha ,I'm running into the same issue,I tried : sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 8
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 8 , to compile with g++8 , it didn't work, can you weigh in on the matter. I understand if it had sometime, so no pressure if your clueless afer two years
